services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shadow-trainer-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
      cache_from:
        - shadow-trainer-api:latest
    image: shadow-trainer-api:latest
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_WORKER_CONCURRENCY=2
      - INCLUDE_2D_IMAGES=true
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - api_tmp:/app/api_backend/tmp_api_output
      - ./api_backend/checkpoint:/app/api_backend/checkpoint
      - ./api_backend/sample_videos:/app/api_backend/sample_videos
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - shadow-trainer-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
      cache_from:
        - shadow-trainer-worker:latest
    image: shadow-trainer-worker:latest
    environment:
      - CELERY_WORKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_WORKER_CONCURRENCY=2
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - api_tmp:/app/api_backend/tmp_api_output
      - ./api_backend/checkpoint:/app/api_backend/checkpoint
      - ./api_backend/sample_videos:/app/api_backend/sample_videos
    restart: unless-stopped
    networks:
      - shadow-trainer-network
    deploy:
      replicas: 2
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: beat
      cache_from:
        - shadow-trainer-beat:latest
    image: shadow-trainer-beat:latest
    environment:
      - CELERY_WORKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./api_backend/checkpoint:/app/api_backend/checkpoint
    restart: unless-stopped
    networks:
      - shadow-trainer-network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: flower
      cache_from:
        - shadow-trainer-flower:latest
    image: shadow-trainer-flower:latest
    ports:
      - "5555:5555"
    environment:
      - CELERY_WORKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - shadow-trainer-network

volumes:
  redis_data:
  api_tmp:

networks:
  shadow-trainer-network:
    driver: bridge
